name: CD
on:
  push:
    tags:
      - v*.*.*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        # with:
        #   # "ref" specifies the branch to check out.
        #   # "github.event.release.target_commitish" is a global variable and specifies the branch the release targeted
        #   ref: ${{ github.event.push.}}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npx lerna bootstrap --no-ci
      - run: npx lerna publish --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
